### ISSUE TITLE
borg-remove shows an error

### ISSUE THREAD

**Issue by DamienCassou** [emacscollective/borg#5]
1. clone emacs.g to a new directory
2. `emacs -Q --load emacs.g/init.elc`
3. `M-x borg-assimilate RET magithub RET`
4. `M-x borg-remove RET magithub RET`

You get 

```
test-completion: Invalid function: ("magithub")
```

**Comment by tarsius** [comment]
I am not able to reproduce this. Could I have a backtrace with it?

I just addressed some potential issues, so maybe that's why I cannot reproduce. But I think I also tried when you reported this.

**Comment by DamienCassou** [comment]
I can still reproduce by following exactly the steps above (adding a `git pull` of `lib/borg` and `make lib/borg` between steps 1 and 2. Instead of step 4, you can just do `M-x borg-remove RET TAB` to reproduce the problem. It appears to be related to completion.

```
Debugger entered--Lisp error: (invalid-function ("magithub"))
  ("magithub")("auto-compile")
  try-completion("" ("auto-compile" "borg" "closql" "dash" "diff-hl" "emacsql" "epkg" "finalize" "git-modes" "magit" "magithub" "packed" "use-package" "with-editor") ("magithub"))
  completion-basic-try-completion("" ("auto-compile" "borg" "closql" "dash" "diff-hl" "emacsql" "epkg" "finalize" "git-modes" "magit" "magithub" "packed" "use-package" "with-editor") ("magithub") 0)
  #[257 "\300\2368\301\242\302\242\303\304\242$\207" [1 ("") (("auto-compile" "borg" "closql" "dash" "diff-hl" "emacsql" "epkg" "finalize" "git-modes" "magit" "magithub" "packed" "use-package" "with-editor")) ("magithub") (0) completion-styles-alist] 6 "\n\n(fn STYLE)"](basic)
  completion--some(#[257 "\300\2368\301\242\302\242\303\304\242$\207" [1 ("") (("auto-compile" "borg" "closql" "dash" "diff-hl" "emacsql" "epkg" "finalize" "git-modes" "magit" "magithub" "packed" "use-package" "with-editor")) ("magithub") (0) completion-styles-alist] 6 "\n\n(fn STYLE)"] (basic partial-completion emacs22))
  completion--nth-completion(1 "" ("auto-compile" "borg" "closql" "dash" "diff-hl" "emacsql" "epkg" "finalize" "git-modes" "magit" "magithub" "packed" "use-package" "with-editor") ("magithub") 0 (metadata))
  completion-try-completion("" ("auto-compile" "borg" "closql" "dash" "diff-hl" "emacsql" "epkg" "finalize" "git-modes" "magit" "magithub" "packed" "use-package" "with-editor") ("magithub") 0 (metadata))
  completion--do-completion(18 18)
  completion--in-region-1(18 18)
  #[1028 "\n\203!\304!\203\202\305!\305\306\"F\307\310!\210\311\"*\207" [minibuffer-completion-predicate minibuffer-completion-table completion-in-region-mode-predicate completion-in-region--data markerp copy-marker t completion-in-region-mode 1 completion--in-region-1] 8 "\n\n(fn START END COLLECTION PREDICATE)"](18 18 ("auto-compile" "borg" "closql" "dash" "diff-hl" "emacsql" "epkg" "finalize" "git-modes" "magit" "magithub" "packed" "use-package" "with-editor") ("magithub"))
  apply(#[1028 "\n\203!\304!\203\202\305!\305\306\"F\307\310!\210\311\"*\207" [minibuffer-completion-predicate minibuffer-completion-table completion-in-region-mode-predicate completion-in-region--data markerp copy-marker t completion-in-region-mode 1 completion--in-region-1] 8 "\n\n(fn START END COLLECTION PREDICATE)"] (18 18 ("auto-compile" "borg" "closql" "dash" "diff-hl" "emacsql" "epkg" "finalize" "git-modes" "magit" "magithub" "packed" "use-package" "with-editor") ("magithub")))
  #[771 ":\2030@\301=\203\300\242\302A\"\303#\207\304@\305\306\307\310\311\312\300!\313\"\314\315%A##\207\304\316\"\207" [(#0) t append nil apply apply-partially make-byte-code 642 "\300\242#\207" vconcat vector [] 7 "\n\n(fn FUNS GLOBAL &rest ARGS)" #[1028 "\n\203!\304!\203\202\305!\305\306\"F\307\310!\210\311\"*\207" [minibuffer-completion-predicate minibuffer-completion-table completion-in-region-mode-predicate completion-in-region--data markerp copy-marker t completion-in-region-mode 1 completion--in-region-1] 8 "\n\n(fn START END COLLECTION PREDICATE)"]] 12 "\n\n(fn FUNS GLOBAL ARGS)"](nil nil (18 18 ("auto-compile" "borg" "closql" "dash" "diff-hl" "emacsql" "epkg" "finalize" "git-modes" "magit" "magithub" "packed" "use-package" "with-editor") ("magithub")))
  completion--in-region(18 18 ("auto-compile" "borg" "closql" "dash" "diff-hl" "emacsql" "epkg" "finalize" "git-modes" "magit" "magithub" "packed" "use-package" "with-editor") ("magithub"))
  completion-in-region(18 18 ("auto-compile" "borg" "closql" "dash" "diff-hl" "emacsql" "epkg" "finalize" "git-modes" "magit" "magithub" "packed" "use-package" "with-editor") ("magithub"))
  minibuffer-complete()
  funcall-interactively(minibuffer-complete)
  call-interactively(minibuffer-complete nil nil)
  command-execute(minibuffer-complete)
  read-from-minibuffer("Uninstall clone: " nil (keymap (10 . minibuffer-complete-and-exit) (13 . minibuffer-complete-and-exit) keymap (menu-bar keymap (minibuf "Minibuf" keymap (tab menu-item "Complete" minibuffer-complete :help "Complete as far as possible") (space menu-item "Complete Word" minibuffer-complete-word :help "Complete at most one word") (63 menu-item "List Completions" minibuffer-completion-help :help "Display all possible completions") "Minibuf")) (27 keymap (118 . switch-to-completions)) (prior . switch-to-completions) (63 . minibuffer-completion-help) (32 . minibuffer-complete-word) (9 . minibuffer-complete) keymap (menu-bar keymap (minibuf "Minibuf" keymap (previous menu-item "Previous History Item" previous-history-element :help "Put previous minibuffer history element in the minibuffer") (next menu-item "Next History Item" next-history-element :help "Put next minibuffer history element in the minibuffer") (isearch-backward menu-item "Isearch History Backward" isearch-backward :help "Incrementally search minibuffer history backward") (isearch-forward menu-item "Isearch History Forward" isearch-forward :help "Incrementally search minibuffer history forward") (return menu-item "Enter" exit-minibuffer :key-sequence "" :help "Terminate input and exit minibuffer") (quit menu-item "Quit" abort-recursive-edit :help "Abort input and exit minibuffer") "Minibuf")) (10 . exit-minibuffer) (13 . exit-minibuffer) (7 . abort-recursive-edit) (C-tab . file-cache-minibuffer-complete) (9 . self-insert-command) (XF86Back . previous-history-element) (up . previous-line-or-history-element) (prior . previous-history-element) (XF86Forward . next-history-element) (down . next-line-or-history-element) (next . next-history-element) (27 keymap (114 . previous-matching-history-element) (115 . next-matching-history-element) (112 . previous-history-element) (110 . next-history-element))) nil nil nil nil)
  completing-read-default("Uninstall clone: " ("auto-compile" "borg" "closql" "dash" "diff-hl" "emacsql" "epkg" "finalize" "git-modes" "magit" "magithub" "packed" "use-package" "with-editor") ("magithub") t nil nil nil nil)
  completing-read("Uninstall clone: " ("auto-compile" "borg" "closql" "dash" "diff-hl" "emacsql" "epkg" "finalize" "git-modes" "magit" "magithub" "packed" "use-package" "with-editor") ("magithub") t)
  borg-read-clone("Uninstall clone: ")
  byte-code("\300\301!C\207" [borg-read-clone "Uninstall clone: "] 2)
  call-interactively(borg-remove record nil)
  command-execute(borg-remove record)
  execute-extended-command(nil "borg-remove" nil)
  funcall-interactively(execute-extended-command nil "borg-remove" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

```
